---
- name: Create VM on RHV
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - ovirt_infra_vars.yml
    - password.yml
  
pre_tasks:
    - name: Login to RHV-M
      ovirt_auth:
        hostname: "{{ engine_url }}"
        username: "{{ engine_user }}"
        password: "{{ engine_password }}"
        ca_file: "{{ engine_cafile | default(omit) }}"
        insecure: "{{ engine_insecure | default(true) }}"
      tags:
        - always

  vars:
    datacenter: DC01
    cluster: Production
    template: rhel-7.5-demo
    vm_memory: 1GiB
    vm_name: vm-3


  tasks:
  - name: Create and run VM from template
    ovirt_vms:
     auth: "{{ ovirt_auth }}"
      name: "{{ vm_name }}"
      template: "{{ template }}"
      cluster: "{{ cluster }}"
      memory: "{{vm_memory}}"
      high_availability: true
      state: present
      wait: yes

  post_tasks:
    - name: Logout from RHV-M
      ovirt_auth:
        state: absent
        ovirt_auth: "{{ ovirt_auth }}"
     tags:
       - always
