---
- name: Create VM on RHV
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - ovirt_infra_vars.yml
    - passwords.yml
  
  pre_tasks:
    - name: Login to RHV-M
      ovirt_auth:
        url: "{{ engine_url }}"
        username: "{{ engine_user }}"
        password: "{{ engine_password }}"
        ca_file: "{{ engine_cafile | default(omit) }}"
        insecure: "{{ engine_insecure | default(true) }}"
      tags:
        - always

  vars:
    wait_for_ip: true

    lab_test_vm:
      cluster: Production
      state: running
      domain: example.com
      template: rhel-7.5-demo
      memory: 1GiB
      cores: 2
      disks:
        - size: 10GiB
          name: data
          storage_domain: vmstore00
          interface: virtio

    vms:
      - name: vm-3
        tag: lab
        profile: "{{ lab_test_vm }}"

  roles:
   - ovirt-vm-infra

  post_tasks:
  - name: Logout from RHV-M
    ovirt_auth:
      state: absent
      ovirt_auth: "{{ ovirt_auth }}"
    tags:
      - always
